### ISSUE TITLE
Advanced Track

### ISSUE THREAD

**Issue by cheahengsoon** [amynic/ainights-sessionowners#1]
Hi Amy,
Any resources for advance track?
Thank you.

**Comment by hnky** [comment]
Hi,
You can find the advanced resources and other links here: https://github.com/hnky/GlobalAINight

**Comment by cheahengsoon** [comment]
@hnky Thank you so much.

**Comment by cheahengsoon** [comment]
@hnky  , 
5 Sept 2019 Global AI Nights will provide new content?
Thank you.
