### ISSUE TITLE
Microsoft Power Apps Issue

### ISSUE THREAD

**Issue by cheahengsoon** [amynic/ainights-sessionowners#4]
Hi Amy,

I got a few Questions to ask about Microsoft Power App.
1. The Power Apps , we need to enable the AI Builder Features ?
2. For the Text Input , the text input is URL?

Thank you.

**Comment by amynic** [comment]
Hi, Thanks for the questions. 

1. When I built the content no extra build features were needed to create this app. You add a connector to the blob storage and that is all that is needed

2. Yes the text input is the file name you wish to store the image as in blob storage. So give it a name like 'dog2' and it will upload to blob storage and then you will have a blob storage URL to use in the logic app

Do this answer your queries?

Thanks
Amy B

**Comment by cheahengsoon** [comment]
@amynic  Thank you so much.
