### ISSUE TITLE
Readme: Predict Tags from Image URL is obsolete

### ISSUE THREAD

**Issue by indcoder** [amynic/ainights-sessionowners#5]
The Logics Apps demo section alludes to the Predict Tags from Image URL which has been deprecated in favour of Classify from Image URL. Subsequently, the dynamic text properties have also been alluding to deprecated one in the text.

**Comment by amynic** [comment]
Thanks for your help @indcoder 👍👍 I have left a few comments in the pull request I want to clarify before merging

**Comment by amynic** [comment]
Thanks for your work on the content its really appreciated - I have merged the changes now :)
